<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Data</name>
   <tag></tag>
   <elementGuidId>0d7c7ac2-17f5-4bac-a3f0-0e04d0555115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='__BVID__517']/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa9b8791-5b52-4dd9-ae85-1731de5817d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/program-kemitraan/hapus-buku/release/20250922213521</value>
      <webElementGuid>3e4afff0-7da3-4c33-8cbe-0578555a6319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>bddf15c9-4631-4952-b2a6-ffd403476d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Data</value>
      <webElementGuid>4a6b0cd7-58cf-4a73-8871-babb9c37ace0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__517&quot;)/tbody[1]/tr[1]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-sm btn-primary&quot;]</value>
      <webElementGuid>50fb888c-64cd-450d-8ed7-30db60ac7606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__517']/tbody/tr/td[5]/a</value>
      <webElementGuid>3cc92c70-82ef-435f-bc03-b57bad277d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Data')]</value>
      <webElementGuid>2423e24b-5597-4f54-aca0-582b49173f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RELEASE'])[1]/following::a[1]</value>
      <webElementGuid>39c31ede-dbe8-4e3e-b783-f1f914707ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor Pusat (Konvensional)'])[2]/following::a[1]</value>
      <webElementGuid>2bf69880-040d-49e7-a9ac-d3830857ee07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/preceding::a[1]</value>
      <webElementGuid>86a64a42-bfa7-49dd-9030-efd2833ab7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::a[1]</value>
      <webElementGuid>118ab60c-19b1-494d-ac65-c5102874331a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Data']/parent::*</value>
      <webElementGuid>45ededaf-9b72-427e-825f-b3d60753a8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/program-kemitraan/hapus-buku/release/20250922213521')]</value>
      <webElementGuid>9dd1b6e4-2e6e-4691-9f1a-466960fd63c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>bbc26aa0-a0f5-4e9b-bba2-f589752fdcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/program-kemitraan/hapus-buku/release/20250922213521' and (text() = 'Lihat Data' or . = 'Lihat Data')]</value>
      <webElementGuid>0ae483b6-315a-4ae0-866b-5cd384d19b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
