<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pengajuan_btn btn-primary btn-block</name>
   <tag></tag>
   <elementGuidId>6c0f8e04-de21-4070-8c87-4025884518ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pkKBPengajuan']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>410c777a-82b9-4729-becc-c251c8688a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/program-kemitraan/kredit-bermasalah-khusus/pengajuan/tambah</value>
      <webElementGuid>0c7bedc5-78ad-4ab3-8119-4a291ef74ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block</value>
      <webElementGuid>f848fd55-3670-4715-b881-69efdc79de8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>eec468cd-aace-4bf0-a72d-b0ed10d014ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>ab0c75ad-e8b4-4d2d-9426-f43aa1b793b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pkKBPengajuan&quot;)/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-md-auto d-print-none&quot;]/a[@class=&quot;btn btn-primary btn-block&quot;]</value>
      <webElementGuid>ab90bd93-f1d0-4649-99b4-d5eb27de740f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pkKBPengajuan']/div/div[2]/a</value>
      <webElementGuid>4afc8282-57a4-4323-b9f9-e08f36a0fc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tambah')]</value>
      <webElementGuid>eac0cfbc-1d64-4433-8e6a-6f68d50a714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan'])[8]/following::a[1]</value>
      <webElementGuid>32e1cb2b-655d-4378-8b6e-c8bd4bbd329b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi Kas'])[2]/following::a[1]</value>
      <webElementGuid>847ae4ec-2d16-4341-b457-dca918e05b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>d593a005-1cf5-4fbd-8aae-15258bd08e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/preceding::a[1]</value>
      <webElementGuid>6dd0ef19-0dc2-4cca-8bcc-4569ae191a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah']/parent::*</value>
      <webElementGuid>3861fd39-393d-4f52-a44e-de5fc15a54a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/program-kemitraan/kredit-bermasalah-khusus/pengajuan/tambah')]</value>
      <webElementGuid>d313a0b1-f837-456a-b67f-bda47751d542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>7e80ed81-8b6b-47a6-b043-07249edb84dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/program-kemitraan/kredit-bermasalah-khusus/pengajuan/tambah' and (text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>105ebd81-2e29-4235-8d7f-2dfa50cada81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
