<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter daftar___BVID__491</name>
   <tag></tag>
   <elementGuidId>5db6428d-e17c-4604-bd56-be0c09e1a8f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__491</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__491']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45668fd8-88d1-4336-9345-346af6834bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fb14a104-c94d-4f1e-b047-302bdc5e072e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Kredit</value>
      <webElementGuid>ee94d6e5-113e-4ad3-9b4c-9fb402679b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 mb-0 form-control</value>
      <webElementGuid>01a28a30-cb15-4ccf-ad8f-af331bcd4de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__491</value>
      <webElementGuid>19a8f979-8fa2-4313-810a-d12893a194d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__491&quot;)</value>
      <webElementGuid>af773e24-2184-4fcd-9a8b-6ecee5506a9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__491']</value>
      <webElementGuid>6c8fb809-7ae9-4c68-8a3c-6881738f3bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pkKBRekomendasi']/div[2]/form/input</value>
      <webElementGuid>65de3840-0e3c-4437-9f62-a282658f0728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>adb36b7a-dec8-45d4-bee3-1427aeceac45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Nomor Kredit' and @id = '__BVID__491']</value>
      <webElementGuid>961bea0e-421b-4b2c-82a3-a4a9b95d5859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
