<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter daftar___BVID__496</name>
   <tag></tag>
   <elementGuidId>28ac7d54-1d86-4023-963d-a97fb5358607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__496']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__496</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eae0b5a4-ed88-4863-8f1a-e5d6ed02cecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fafaa04-d27b-4bd3-b457-336fcb75eb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Kredit</value>
      <webElementGuid>7d282b5b-9b77-46b6-989e-34b375e7c12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 mb-0 form-control</value>
      <webElementGuid>d8768d21-20f4-4f3f-a9d1-9953066140b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__496</value>
      <webElementGuid>6e6dea83-dbb0-4a79-8867-c5fc0a3eb553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__496&quot;)</value>
      <webElementGuid>e2275c30-63f6-4007-b5a0-ebb7a246baa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__496']</value>
      <webElementGuid>1e5a7582-2de5-4288-81a9-f62cb01428ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pkKBTambahPengajuan']/div[3]/form/input</value>
      <webElementGuid>46464047-2942-4026-b06f-fd0f8cee594c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d7f8224-31cb-48ab-8e0b-915d51d9fdd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nomor Kredit' and @id = '__BVID__496']</value>
      <webElementGuid>4b63c442-975b-4afd-a6f3-bf25ca11d938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
