<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter daftar___BVID__512</name>
   <tag></tag>
   <elementGuidId>adafed4d-fb98-4608-9944-aa7e3529eba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__512</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__512']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3193488-ec0a-4cb6-ae32-d381f213ce37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20742671-e797-4ce6-967d-fc98e7c7cba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama MB</value>
      <webElementGuid>ec7cbbc3-9c20-478d-836d-8f9645288e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 mb-0 form-control</value>
      <webElementGuid>bffc8f0e-5f86-44af-8267-3461e1eec4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__512</value>
      <webElementGuid>f199df80-1350-401d-abff-0f2d7630653f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__512&quot;)</value>
      <webElementGuid>a6a6de9c-f9f7-46e6-8b91-6aab55c4a047</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__512']</value>
      <webElementGuid>7f1a41a7-50db-48d5-8075-0f95e3326764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pkKBRekomendasi']/div[2]/form/input[2]</value>
      <webElementGuid>7d1728f8-110c-453c-8f38-b7b2bdb3e839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>4759fc51-a5ba-4bf4-8396-28476ab38cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nama MB' and @id = '__BVID__512']</value>
      <webElementGuid>ecb8bbc4-8221-4d21-9e4b-19c71acaaf46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
