<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter daftar___BVID__511</name>
   <tag></tag>
   <elementGuidId>11f6bb57-dff9-4966-a6a8-b123ea7050b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__511</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__511']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1a93025-775c-4d2f-8857-eadf56494f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c1750d9e-a7d2-47dd-968f-c6b8f86ffb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Kredit</value>
      <webElementGuid>d497cae4-4974-472a-a4d2-a920886426c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 mb-0 form-control</value>
      <webElementGuid>05bddd8a-4b68-44a5-b16e-002231f9ecc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__511</value>
      <webElementGuid>25d3142c-8b09-4b82-83c8-dc68407e7a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__511&quot;)</value>
      <webElementGuid>ad786026-23b4-4a1e-9499-3aa4fdf6b54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__511']</value>
      <webElementGuid>976bca94-266c-4e66-ad0b-b961756d5b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pkKBRekomendasi']/div[2]/form/input</value>
      <webElementGuid>b90ed083-e944-4cc3-a268-e1178d0acdd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5b035771-a426-4e9e-99e8-a6c5343404ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Nomor Kredit' and @id = '__BVID__511']</value>
      <webElementGuid>c083d5b8-e7c3-48a7-9e2e-4edc08b499ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
