<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Konsolidasi</name>
   <tag></tag>
   <elementGuidId>6358ffb4-61b6-45c7-bc38-d8836b78e646</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='laporanMBBermasalah']/div[2]/form/div/div[4]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.custom-control-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f68fbcc8-8f8c-4203-965d-c26244ad9708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>konsolidasi</value>
      <webElementGuid>100ac0fe-0d3c-4ab6-ac2d-0a8ed46fa779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>36cb7dcc-9fd7-47bf-bd35-c89a84ed4302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konsolidasi</value>
      <webElementGuid>ddef4bd7-7a59-4e45-8ab9-42672bbf8c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;laporanMBBermasalah&quot;)/div[@class=&quot;mb-3&quot;]/form[1]/div[@class=&quot;form-row&quot;]/div[@class=&quot;mb-2 col-md-3&quot;]/div[@class=&quot;custom-control custom-checkbox&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>2e91b945-bd56-4141-b195-5818cc46e724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='laporanMBBermasalah']/div[2]/form/div/div[4]/div/label</value>
      <webElementGuid>305319af-64f3-4505-af0d-e4cbeb8cf0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[6]/following::label[1]</value>
      <webElementGuid>d085ad0b-7fef-4885-b2c4-e682215cb42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[6]/following::label[1]</value>
      <webElementGuid>023d1c7b-1be5-418e-ae3c-2ec0fec27d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[2]/preceding::label[1]</value>
      <webElementGuid>e28681b3-99e6-4913-b1ee-c38c9f254a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor'])[1]/preceding::label[1]</value>
      <webElementGuid>112e5c7f-87c0-4a99-9cc3-b3755c630364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Konsolidasi']/parent::*</value>
      <webElementGuid>109c6a30-b86a-4721-ba03-e896faad5af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label</value>
      <webElementGuid>1ca68423-5b59-44e5-becb-429c4a7b4364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Konsolidasi' or . = 'Konsolidasi')]</value>
      <webElementGuid>177de474-e37d-4a61-ad5c-52db60f28c6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
