<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Setujui</name>
   <tag></tag>
   <elementGuidId>a4a49d2f-afb9-4970-ae2b-edf49707ac13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.mr-2.btn-primary > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='modalApproval___BV_modal_footer_']/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4fb6925-77bb-4cdc-98f8-90b6559d5816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Setujui</value>
      <webElementGuid>49093d5b-39d2-4066-a652-acf8017afe0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalApproval___BV_modal_footer_&quot;)/div[@class=&quot;w-100&quot;]/button[@class=&quot;btn mr-2 btn-primary&quot;]/span[1]</value>
      <webElementGuid>16a37450-b915-47dc-8573-3cde996e3e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='modalApproval___BV_modal_footer_']/div/button/span</value>
      <webElementGuid>b2d2c1b9-0308-486a-aa03-c777b3d40616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[1]</value>
      <webElementGuid>59357321-85cd-4c41-83fc-21bf3f924932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::span[1]</value>
      <webElementGuid>e4eaee9b-60ba-4ab1-9555-cc2140fc61cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Setujui']/parent::*</value>
      <webElementGuid>08e1ea1e-e1de-4a93-a750-8edf3f5ca604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span</value>
      <webElementGuid>6052f837-7e97-4359-be33-28e29f647595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Setujui' or . = 'Setujui')]</value>
      <webElementGuid>923ac31c-1ffb-4ac7-bd5d-edb4821e6068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
