<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1100106150020</name>
   <tag></tag>
   <elementGuidId>8de8ebbc-fcc4-45cf-9963-3b0bc1d4a65f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='__BVID__493']/tbody/tr[3]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0efc9b98-b763-4756-bd72-c4e8bd78a34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>95dc2b65-e91d-44b5-a1d2-cf79e0d6bf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0843aea5-09ec-41a1-bfa9-a44d2028b3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1100106150020</value>
      <webElementGuid>3b45ac4d-fc26-4067-8510-700394cb36c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__493&quot;)/tbody[1]/tr[3]/td[1]</value>
      <webElementGuid>17728fd5-a820-464f-96ca-5688a33a744c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__493']/tbody/tr[3]/td</value>
      <webElementGuid>0588ed34-4dff-439e-a3f5-636d0448e9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wilayah 2 Pekanbaru'])[1]/following::td[2]</value>
      <webElementGuid>160946a9-81ff-4ba6-be01-6e985d676345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KREDIT BERMASALAH'])[2]/following::td[3]</value>
      <webElementGuid>99ba1696-1034-47bf-b9d3-bb4e2065f0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mustapa'])[1]/preceding::td[1]</value>
      <webElementGuid>718ae82c-2bfc-4f00-90f2-e9abf83b715a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buana Maru'])[1]/preceding::td[2]</value>
      <webElementGuid>3ed8921f-7246-477b-a72b-bd515369d155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1100106150020']/parent::*</value>
      <webElementGuid>5d6f0b6a-a4b0-468f-b56a-806f28a56400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>db3f9089-baa4-4a63-a67e-0eee05ec9c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1100106150020' or . = '1100106150020')]</value>
      <webElementGuid>ca385951-76b8-42b9-a5d3-a301019fc1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__495']/tbody/tr[3]/td</value>
      <webElementGuid>f001edf6-3da4-4d84-858a-32b0ce9cecbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REKOMENDASI'])[2]/following::td[1]</value>
      <webElementGuid>c37150b9-66ab-47be-93c5-60976f653393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KREDIT BERMASALAH'])[2]/following::td[2]</value>
      <webElementGuid>5f9dcdf4-f065-4f07-bc76-8387b1478588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKTIF'])[3]/preceding::td[5]</value>
      <webElementGuid>d9586c13-e120-4d8d-83e7-237b9c9a23b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
