<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1100106970010</name>
   <tag></tag>
   <elementGuidId>0c66c1e2-fbd4-4ada-890e-8773da91782e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='__BVID__494']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>44636633-b12a-4212-ab29-767a98052862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>e350bcf0-faeb-4ab4-b37e-ddfa6ac470f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9f8a4bab-9437-4b22-be6e-758c12ea65bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1100106970010</value>
      <webElementGuid>905cb31c-5d3e-407e-95ec-fd4e49e0438a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__494&quot;)/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>d913e5fd-6950-4a0b-97b8-ccae89001d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__494']/tbody/tr/td</value>
      <webElementGuid>4f321237-a33f-4f0c-bd86-6bb3171b9b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajukan Reklas'])[1]/following::td[1]</value>
      <webElementGuid>095bf826-fcb9-448e-8e84-473cd64fc79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Cabang Asal'])[1]/following::td[1]</value>
      <webElementGuid>10ddc05b-206e-4105-ac01-4b1dc50e1606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1100106970010']/parent::*</value>
      <webElementGuid>74b06cfa-4799-4f41-aeac-3032232ef49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>d1c8d57e-a548-4a63-97a8-38cb3e7b8635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1100106970010' or . = '1100106970010')]</value>
      <webElementGuid>b3f38b3b-e415-4f20-92a5-70691fef651d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__527']/tbody/tr/td</value>
      <webElementGuid>2d6c4fa2-4526-49b5-ae1c-0e2b7fb6f0e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
