<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__alasan-approval</name>
   <tag></tag>
   <elementGuidId>471ef4a2-1365-4431-ac3d-baa664368f43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alasan-approval</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='alasan-approval']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1b692f13-42fc-4737-8733-0d2b7827505b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alasan-approval</value>
      <webElementGuid>c561d708-5565-4dc3-b7c4-8543368daadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan catatan</value>
      <webElementGuid>1500c087-fbb2-4c94-8505-6f8554a34445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>cb6dc5b8-0044-402a-9a6e-642c4b87c0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wrap</name>
      <type>Main</type>
      <value>soft</value>
      <webElementGuid>f0e57c24-86a4-40a6-9dbc-400dd5e6a1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5fef2cb9-e72e-4c59-b3ab-1409d46db1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97c37fad-8ad7-4e12-8568-ad45d47e65e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f9d7c47-a8cd-44a1-b434-4fcf32a4e574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alasan-approval&quot;)</value>
      <webElementGuid>1753261a-cad7-4c02-8dc6-c92f8ab659ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='alasan-approval']</value>
      <webElementGuid>3da2c6bd-9beb-4d5d-9f9a-d22e0c90fea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalApproval___BV_modal_body_']/div/textarea</value>
      <webElementGuid>be6285ad-6999-4457-9c19-33fb0e2ca9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e31159c1-aba8-4cc8-8223-08291b798995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'alasan-approval' and @placeholder = 'Masukkan catatan']</value>
      <webElementGuid>8fba1881-f38c-4aec-a3d0-e41ee3620cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__609']/div/textarea</value>
      <webElementGuid>9b16b8df-10d6-4416-a3d8-319ceba5cde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'alasan-approval' and @placeholder = 'Alasan' and @type = 'text']</value>
      <webElementGuid>802938ba-35ed-4013-a0f1-0b7151010066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__599']/div/textarea</value>
      <webElementGuid>29cab3bf-1ab1-4c18-b48d-1a6bc3fd7e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__608']/div/textarea</value>
      <webElementGuid>f41550af-1d57-422b-823d-64ce2e9a4404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__510']/div/textarea</value>
      <webElementGuid>0175d665-c5d4-4231-970e-f4a928bfae05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__588']/div/textarea</value>
      <webElementGuid>8fb4402a-25a6-4d0c-ae89-42660cfb58be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__585']/div/textarea</value>
      <webElementGuid>d4e479f8-91f7-4572-99c0-c1918dbc969c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__582']/div/textarea</value>
      <webElementGuid>28780411-23a0-4dc4-941a-d966b1228d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__566']/div/textarea</value>
      <webElementGuid>b13ca2c5-fd18-4536-97b2-ef83d9016490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
