<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea____BVID__523</name>
   <tag></tag>
   <elementGuidId>764a5247-21a9-4432-bb13-48cc9e041dae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__523</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='__BVID__523']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>da8d89e0-20b2-4d59-9def-0e6ba9f8352d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alasan Pengajuan</value>
      <webElementGuid>e94b4ae6-f863-40bc-9993-84ac1e1e5e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e177e37d-a2ec-462f-a456-71aceff780b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wrap</name>
      <type>Main</type>
      <value>soft</value>
      <webElementGuid>c773d644-a791-40b2-b949-5a28e03ef934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dc15402e-e1fc-4bcc-8e26-e880034eb5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb2f82e5-8d85-44f3-8e82-f09860df0f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__523</value>
      <webElementGuid>9c664ae7-8a52-4f72-991a-a4f5aea8a120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__523&quot;)</value>
      <webElementGuid>27a8b007-83bf-4bf2-ad9e-142cd588b230</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='__BVID__523']</value>
      <webElementGuid>40b5c247-161e-4e76-ac2f-93e14457d53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__522']/div/textarea</value>
      <webElementGuid>bf67ace2-3145-4a68-b3c6-aef0d0d53a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a2d32303-5fc2-455b-bd16-2d971f5e623f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Alasan Pengajuan' and @type = 'text' and @id = '__BVID__523']</value>
      <webElementGuid>552a2c6d-c6c9-4660-ae08-c072014fb814</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
