<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__alasan</name>
   <tag></tag>
   <elementGuidId>b60f9c7e-799a-4207-a72a-b1bb1d71badb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alasan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='alasan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d30d1882-1336-44aa-966a-a23e00cae1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alasan</value>
      <webElementGuid>edafd95d-ba1d-420a-be96-d3c6dbcaf35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alasan</value>
      <webElementGuid>066a733c-ae53-44b9-a68e-1affd2988f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e8d00177-6a44-49e6-90a8-9cd9f3de9271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wrap</name>
      <type>Main</type>
      <value>soft</value>
      <webElementGuid>bcb6826b-cc96-4827-a0fd-eca000890b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>06c8a920-b574-4718-93b1-8e194498fb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alasan&quot;)</value>
      <webElementGuid>2ca1bc2e-4b5f-4259-a786-ac32fa4c21b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='alasan']</value>
      <webElementGuid>7e141537-09f9-4e08-808c-b58daef101ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-alasan___BV_modal_body_']/textarea</value>
      <webElementGuid>293074b0-03d8-4ab1-8710-e66051cf9580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>292e654f-12e8-43c5-a0de-4eb2ee46befa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'alasan' and @placeholder = 'Alasan']</value>
      <webElementGuid>4ec4d07c-9dc7-4548-8a24-7f7a5d8d90ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
